### PR TITLE
Feature: import and split resource browser from ENMap-Box

### PR DESCRIPTION
**Pull request by Guts**
@jakimowb I push here my WIP on importing and splitting your code. Sorry for the mess, it's an interrupted work :sweat_smile:.

### CODE REVIEW

**Comment by jakimowb** [comment]
@Guts I am working on it to clean my code and get it running

**Comment by jakimowb** [comment]
@Guts I am done. Using unittest, not pytest, all tests run well locally. 

[grafik](https://user-images.githubusercontent.com/1404870/226758668-27207fe1-e434-4371-90df-3b66f2287367.png)

grafik

However, I was not able to find out why the test fail on github. The `ModuleNotFoundError: No module named 'qgis'` looks like the PYTHONPATH is not set right.

```
_____________ ERROR collecting tests/unit/test_resource_browser.py _____________
ImportError while importing test module '/home/runner/work/qgis-plugin-resource-browser/qgis-plugin-resource-browser/tests/unit/test_resource_browser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/test_resource_browser.py:3: in <module>
    from qgis.PyQt.QtWidgets import QWidget
E   ModuleNotFoundError: No module named 'qgis'
```

**Comment by Guts** [comment]
Hey @jakimowb ,

Thank again for your work. I've made some fixes but still not fixed the resource browser test.

Some notes:

- I've picked and set an icon for the Resource Browser. Feel free to change this.
- as stipulated in [the development guide](https://guts.github.io/qgis-plugin-resource-browser/development/testing.html), tests are splitted between those requiring QGIS/Qt and those which are really independent ("pure" unit). No worries, I just remove one of the duplicated `test_resource_browser.py` from the `qgis/unit` folder and it fixes the unit test job
- when you write:

  > Using unittest, not pytest, all tests run well locally.

  I can't manage to run locally (Ubuntu LTS):

  ```sh
  > python -m unittest tests.qgis.test_resource_browser
  QWidget: Must construct a QApplication before a QWidget
  Abandon (core dumped)
  ```

- the resource browser is showing every resource in a Qt application installed, not only the QGIS related ones (see below). I guess it's occurring on systems where the used Qt is the  one installed at sys level (typically on Linux) and not packaged in QGIS (Windows, flatpack...):

  image

  Even if we could consider that as an opportunity, I prefer that we keep a focus on QGIS resources only. Or at least just the default Qt icons which also can be accessed on every system.

**Comment by jakimowb** [comment]
Hi @Guts 

I added functionallity to filter the resource prefixes and file types. By default, theses settings should show PyQGIS-only icons only:
grafik (screenshot Qt Desginer)

I tried to define theses default values as List[str] in PlgSettingsStructure:

```
@dataclass
class PlgSettingsStructure:
    """Plugin settings structure and defaults values."""

    # global
    debug_mode: bool = False
    version: str = __version__

    filter_prefixes: bool = True
    filter_filetypes: bool = True

    prefix_filters: list = field(default_factory=lambda: [
        ':/images/',
        ':/oauth2method/',
        ':/topology',
        ':/geometrychecker/',
        ':/offline_editing/',
        ':/qt-project.org/'])

    filtetype_filters: list = field(default_factory=lambda: [
        'svg', 'png', 'ico', 'xpn'])
```
but this fails in the generic function to read/write from QgsSettings:```


  File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\pyqgis_resource_browser\toolbelt\preferences.py", line 65, in get_plg_settings
    settings.value(key=i.name, defaultValue=i.default, type=i.type)
TypeError: unable to convert a QVariant of type 1024 to a QMetaType of type 9
```
Do you have an idea to allow the PlgSettingsStructure to store default lists and read/write the from/to QgsSettings?

**Comment by jakimowb** [comment]
I also added a __main__.py that allows to start the resource browser from plain python.

**Comment by jakimowb** [comment]
Great that you added an icon 👍 and that it is the same as used in https://pyqgis-icons-cheatsheet.geotribu.fr

That allowed me to understand that the yellow and blue lines are actually pythons. Unfortunatelly this becomes hardly visible in typical icon sizes like 32x32 pixel or in the browser tab.
grafik

Maybe you can increase the snake's diameter?

A combination of the QGIS "Q" and the more abstract python snakes (like here  
grafik) could also be well recognizable with smaller icon sizes.

**Comment by Guts** [comment]
Woa @jakimowb, you did a lot of job!

Maybe it's too much for one Pull Request though? Do you mind if we work with in a more atomic way? 

I suggest that we merge this PR with only the basic resource browser and make another one to discuss about the `__main__` launcher and the filters in preferences?

I think we can ignore test because it's not an end-user plugin and the functional scope is not so complicated. What do you think?

**Comment by jakimowb** [comment]
@Guts I agree with you and removed the __main__.py from the PR branch. 

However, I have still the problem to read and store a list of strings using the PlgOptionsManager.

```
  File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\tests\qgis\test_resource_browser.py", line 32, in test_resource_browser
    B = ResourceBrowser()
  File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\pyqgis_resource_browser\gui\resource_browser.py", line 90, in __init__
    settings = PlgOptionsManager.get_plg_settings()
  File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\pyqgis_resource_browser\toolbelt\preferences.py", line 68, in get_plg_settings
    settings.value(key=i.name, defaultValue=i.default, type=i.type)
TypeError: unable to convert a QVariant of type 1024 to a QMetaType of type 9

```

**Comment by Guts** [comment]
I'll have a look, I'm pretty sure it's possible. I'm on holydays, so it has to wait for my return next Monday.

**Comment by Guts** [comment]
> Great that you added an icon 👍 and that it is the same as used in https://pyqgis-icons-cheatsheet.geotribu.fr
> 
> That allowed me to understand that the yellow and blue lines are actually pythons. Unfortunatelly this becomes hardly visible in typical icon sizes like 32x32 pixel or in the browser tab.
> grafik
> 
> Maybe you can increase the snake's diameter?
> 
> A combination of the QGIS "Q" and the more abstract python snakes (like here  
> grafik) could also be well recognizable with smaller icon sizes.

Actually I'm reusing an existing logo (see credits page https://pyqgis-icons-cheatsheet.geotribu.fr/credits/#credits).

Good idea to mix Python and QGIS logos. If you feel inspired, move on to edit it or create a new one. I could also apply it to the related website.

Sorry, I'm too bad at design to help on this.

**Comment by Guts** [comment]
> @Guts I agree with you and removed the __main__.py from the PR branch. 

Thanks! 

> However, I have still the problem to read and store a list of strings using the PlgOptionsManager.
> 
> ```
>   File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\tests\qgis\test_resource_browser.py", line 32, in test_resource_browser
>     B = ResourceBrowser()
>   File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\pyqgis_resource_browser\gui\resource_browser.py", line 90, in __init__
>     settings = PlgOptionsManager.get_plg_settings()
>   File "D:\Repositories\qgisplugins\qgis-plugin-resource-browser\pyqgis_resource_browser\toolbelt\preferences.py", line 68, in get_plg_settings
>     settings.value(key=i.name, defaultValue=i.default, type=i.type)
> TypeError: unable to convert a QVariant of type 1024 to a QMetaType of type 9
> 
> ```
> The problem seems to be the 
> ```
> @dataclass
> class PlgSettingsStructure:
> ```
> which does not support lists. 

Finally, I took a few minutes to fix the bug in settings getter.

I'll have a look later or Monday on settings setter.

I'm gonna disable test on CI.

**Comment by jakimowb** [comment]
@Guts I revised the filtering. Changes to the config page are now applied as intended and immediately to the ResourceBrowser. 
I think it's now ready to get merged into the main branch.

**Comment by Guts** [comment]
Yeah, here we go!

Next steps:

- documentation
- publication: if you want, we publish the plugin under your osgeo nickname. It sounds fair enough to me because I just made the boilerplate. If you agree, you have to set your osgeo username and password as CI Actions secrets in repository settings. 
- broadcasting

**Pull request merged**
